version: '3.3'

services:
  mongodb:
    container_name: actions-db
    image: mongo:4.4-bionic
    command: mongod --serviceExecutor adaptive
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: wDjHMaje8y_Ai_42izjv!Uv-2PPscwdQ
      MONGO_USERNAME: admin
      MONGO_PASSWORD: wDjHMaje8y_Ai_42izjv!Uv-2PPscwdQ
      MONGO_DB: actions
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - mongodbdata:/data/db

  client:
    image: ghcr.io/smart-chef-dev/sc-actions-client/sc-actions-client:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  server:
    image: docker.pkg.github.com/smart-chef-dev/sc-actions/sc-actions:latest
    environment:
      - DATABASE_CONNECTION_STRING=<STRING>
      - TELEGRAM_BOT_KEY=<API_KEY>
      - FRONTEND_URL=https://smartchef.pl/
    ports:
      - "3000:3000"


volumes:
  mongodbdata:

networks:
  default:
    external:
      name: mongo-network
