version: '3.3'

services:
  mongodb:
    container_name: actions-db
    restart: unless-stopped
    image: mongo:4.4-bionic
    command: mongod --serviceExecutor adaptive
    environment:
      - DOPPLER_TOKEN
      - DOPPLER_PROJECT
      - DOPPLER_CONFIG
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DB
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - mongodbdata:/data/db
    labels:
      reproxy.enabled: no

  server:
    image: ghcr.io/smart-chef-dev/sc-actions/sc-actions:${SERVER_VERSION}
    restart: unless-stopped
    hostname: api
    container_name: api
    environment:
      - DOPPLER_TOKEN
      - DOPPLER_PROJECT
      - DOPPLER_CONFIG
      - DATABASE_CONNECTION_STRING
      - TELEGRAM_BOT_KEY
      - TELEGRAM_START_CMD_DELIMITER
      - FRONTEND_URL
      - BACKEND_URL
      - PATH_TO_RESTAURANT_PHOTOS
      - STRIPE_KEY
      - STRIPE_API_VERSION
      - JWT_SECRET
      - JWT_EXPIRES_IN
    volumes:
      - resturants_data:/usr/src/app/public
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}

  reproxy:
    image: ghcr.io/smart-chef-dev/sc-actions-client/sc-actions-client:${CLIENT_VERSION}
    restart: unless-stopped
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/ssl:/srv/var/ssl
    environment:
      - TZ=Europe/London
      - ASSETS_SPA=true
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=true
      - DEBUG=true
      - SSL_TYPE=auto
      - SSL_ACME_FQDN=${DOMAIN_NAME}
      - SSL_ACME_LOCATION=/srv/var/ssl
      - LOGGER_STDOUT=true
      - ASSETS_LOCATION=/www
      - TIMEOUT_RESP_HEADER=640s
      - TIMEOUT_WRITE=640s
      - TIMEOUT_IDLE=640s
      - TIMEOUT_DIAL=640s
      - TIMEOUT_KEEP_ALIVE=640s
      - MAX_SIZE=0
    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - server

  logger:
    container_name: logger
    hostname: logger
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    labels:
      reproxy.enabled: no

volumes:
  mongodbdata:
  resturants_data:
