version: '3.3'

services:
  mongodb:
    container_name: actions-db
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    command: [--auth]

  client:
    image: docker.pkg.github.com/smart-chef-dev/sc-actions-client/sc-actions-client:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/ssl/certs:ro"

  server:
    image: docker.pkg.github.com/smart-chef-dev/sc-actions/sc-actions:latest
    environment:
      - DATABASE_CONNECTION_STRING=<STRING>
      - TELEGRAM_BOT_KEY=<API_KEY>
    ports:
      - "3000:3000"


volumes:
  mongodbdata:

networks:
  default:
    external:
      name: mongo-network
