---
- hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    - name: Add Doppler apt Key
      apt_key:
        url: https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key
        state: present

    - name: Add Doppler Repository
      apt_repository:
        repo: deb https://packages.doppler.com/public/cli/deb/debian any-version main
        state: present

    - name: Update apt and install doppler
      apt: update_cache=yes name=doppler state=latest

    - name: Doppler login
      shell: |
        export HISTIGNORE='doppler*'
        doppler configure set token '{{ service_tokens }}'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
