name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm i

      - name: Run ESLint
        run: npm run lint

      - name: Run test
        run: npm run test

      - name: Run build
        run: npm run build