name: Docker-publish

on: [release]

jobs:
  deploy-to-do:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Start updater
        run: curl http://${{ secrets.HOST }}:8081/update/update-server/${{ secrets.UPDATER_KEY }}

  deploy-to-do-dev:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2

      - name: Start updater
        run: curl http://${{ secrets.HOST_DEV }}:8081/update/update-server/${{ secrets.UPDATER_KEY }}
